# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concentrate', '0002_auto_20170324_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='db_file',
        ),
    ]
